debug_features: False # set to True to determine feature domain bounds

#fitness_type: "meanAvgReward"
#meanAvgRewardDomain: [0., 1000.]
#
#features_list: ["meanDistance", "meanHeadStability"]
#meanDistanceDomain: [0., 1.]
#meanHeadStabilityDomain: [0., 1.]


main_algorithm_name: algoQD

containers:
    cont0:
        type: Grid                               # The type of the container (e.g. Grid, CVTGrid, Container, NoveltyArchive, ...)
        name: cont0                              # The name of the container. Optional. Default to the parent key (here also 'cont0')
        shape: [25, 25]                          # The number of bins for each feature
        max_items_per_bin: 1                     # The number of items in each bin of the grid
#        fitness_domain: [[-200., 350.]]           # The domain of each fitness objective (here we only have one objective)
#        features_domain: [[0., 50.], [0., 2.5]]  # The domain of each feature

algorithms:
    # Default parameter values for each algorithm
    optimisation_task: max 
    dimension: 16
    ind_domain: [0., 42.]   # == activation domain
    container: cont0        # The container to use to store individuals told to the optimisers

    algoQD:
        type: RandomSearchMutPolyBounded
        budget: 1000       # The total number of allowed evaluations for this algorithm
        batch_size: 100     # The number of evaluations in each subsequent batch
        sel_pb: 0.7         # The probability of performing selection+variation instead of initialising a new genome
        init_pb: 0.3        # The probability of initiating a new genome instead of performing selection
        mut_pb: 0.1         # The probability of mutating each value of the genome of a selected individual
        eta: 20.            # The ETA parameter of the polynomial mutation (as defined in the origin NSGA-II paper by Deb.). It corresponds to the crowding degree of the mutation. A high ETA will produce mutants close to its parent, a small ETA will produce offspring with more changes.

# MODELINE "{{{1
# vim:expandtab:softtabstop=4:shiftwidth=4:fileencoding=utf-8
# vim:foldmethod=marker
